// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - tanstackStart, viteReact, tailwindcss, tsConfigPaths, nitro (build-only using cloudflare as a default target),
//     componentTagger (dev-only), VITE_* env injection, @ path alias, React/TanStack dedupe,
//     error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... }, etc... }) if needed.
import { defineConfig } from "@lovable.dev/vite-tanstack-config";

export default defineConfig({
  vite: {
    // The remaining >500 kB chunks are server-only vendor modules generated by
    // TanStack Start (router and Tiptap core). The client/editor chunks stay
    // below the default threshold; keep the warning focused on real client
    // regressions instead of repeating an unavoidable SSR vendor warning.
    build: { chunkSizeWarningLimit: 650 },
    // Base44 serves the dev server through a proxy whose Host header is an
    // internal hostname that can't be allow-listed ahead of time, so permit
    // any host (dev only — this has no effect on production builds).
    server: { allowedHosts: true },
  },
  tanstackStart: {
    // Redirect TanStack Start's bundled server entry to src/server.ts (our SSR error wrapper).
    // nitro/vite builds from this
    server: { entry: "server" },
  },
});
