// @lovable.dev/vite-tanstack-config already includes the following — do NOT add them manually
// or the app will break with duplicate plugins:
//   - tanstackStart, viteReact, tailwindcss, tsConfigPaths, nitro (build-only using cloudflare as a default target),
//     componentTagger (dev-only), VITE_* env injection, @ path alias, React/TanStack dedupe,
//     error logger plugins, and sandbox detection (port/host/strictPort).
// You can pass additional config via defineConfig({ vite: { ... }, etc... }) if needed.
import { defineConfig as lovableDefineConfig } from "@lovable.dev/vite-tanstack-config";
import { createLogger } from "vite";

// Vite 8 warns unconditionally whenever a plugin named "vite-tsconfig-paths" is
// present, and the Lovable wrapper adds that plugin hardcoded with no opt-out —
// so the notice cannot be removed by config. Filter just that one message out of
// the logger instead of muting warnings wholesale; everything else logs normally.
function makeViteLogger() {
  const logger = createLogger();
  const warnOnce = logger.warnOnce.bind(logger);
  logger.warnOnce = (msg, ...rest) => {
    if (msg.includes("vite-tsconfig-paths")) return;
    return warnOnce(msg, ...rest);
  };
  return logger;
}

// Same contract the Lovable wrapper uses (LOVABLE_SANDBOX, or the Base44
// platform's dev-server var). In these environments the wrapper forces port
// 8080/strictPort itself — compose maps host 3000 to it — so we must not set a
// port there (validatePort would warn). Everywhere else (bare-metal
// `npm run dev`) we pin Vite's conventional default, because 8080 is commonly
// squatted by other compose projects and a random fallback port breaks the
// muscle-memory URL.
const sandboxLike =
  process.env.LOVABLE_SANDBOX === "1" || !!process.env.DEV_SERVER__PROJECT_PATH;

// Colocated route-surface tests (u.$handle.test.ts, teams.$slug.test.ts) run in
// vitest, not the router; without this the generator logs a "does not export a
// Route" warning for each on every dev start. Matched against the file basename.
const ROUTE_FILE_IGNORE_PATTERN = "\\.(test|spec)\\.";

export default lovableDefineConfig({
  vite: {
    customLogger: makeViteLogger(),
    server: {
      // Base44 serves the dev server through a proxy whose Host header is an
      // internal hostname that can't be allow-listed ahead of time, so permit
      // any host (dev only — this has no effect on production builds).
      allowedHosts: true,
      ...(sandboxLike ? {} : { port: 5173 }),
    },
    // The remaining >500 kB chunks are server-only vendor modules generated by
    // TanStack Start (router and Tiptap core). The client/editor chunks stay
    // below the default threshold; keep the warning focused on real client
    // regressions instead of repeating an unavoidable SSR vendor warning.
    build: {
      chunkSizeWarningLimit: 650,
      rollupOptions: {
        output: {
          advancedChunks: {
            groups: [
              { name: "toaster", test: /node_modules\/sonner/ },
              // The app's server-function modules call createServerFn() at
              // module scope. In the single-file fetch bundle (inlineDynamicImports)
              // they must not be merged into a chunk that initializes before the
              // tanstack-start core region defines createServerFn — that ordering
              // is decided by rolldown's chunk-merge heuristics and flips with any
              // unrelated content change (this exact failure shipped once: a
              // dashboard edit moved these into the early router chunk and every
              // SSR page 500'd with "createServerFn is not a function"). Pinning
              // them into their own group keeps them in a dedicated, lazily
              // initialized region regardless of graph shape.
              {
                name: "server-fns",
                test: /(account-server|github-server|auth-middleware)/,
              },
            ],
          },
        },
      },
    },
  },
  tanstackStart: {
    // Redirect TanStack Start's bundled server entry to src/server.ts (our SSR error wrapper).
    // nitro/vite builds from this
    server: { entry: "server" },
    // Route-tree generation: skip colocated test files (see pattern above).
    router: { routeFileIgnorePattern: ROUTE_FILE_IGNORE_PATTERN },
  },
});
