#!/usr/bin/env bash
# Base44 start script — brings up the full local stack for Tethyr.
#
# 1. Starts the local Supabase stack (postgres, auth, rest, storage, realtime,
#    kong) via the `supabase` CLI. Idempotent on a warm volume: it only applies
#    migrations + seed on first init, then just starts the containers.
# 2. Reads the live API keys from `supabase status` (they are generated per
#    local instance) and writes them to .env.supabase-runtime.
# 3. Starts the app (docker-compose.base44.yml) from the cloned source with
#    live reload.
set -euo pipefail

cd "$(dirname "$0")/.."

echo "[base44] Starting local Supabase stack…"
npx supabase start

echo "[base44] Reading live Supabase keys…"
STATUS_ENV="$(npx supabase status -o env)"
PUBLISHABLE_KEY="$(printf '%s\n' "$STATUS_ENV" | sed -n 's/^PUBLISHABLE_KEY="\(.*\)"$/\1/p')"
SECRET_KEY="$(printf '%s\n' "$STATUS_ENV" | sed -n 's/^SECRET_KEY="\(.*\)"$/\1/p')"

if [ -z "$PUBLISHABLE_KEY" ] || [ -z "$SECRET_KEY" ]; then
  echo "[base44] ERROR: could not read Supabase keys from 'supabase status'." >&2
  exit 1
fi

SUFFIX="${BASE44_PUBLIC_HOST_SUFFIX:-}"
if [ -z "$SUFFIX" ]; then
  echo "[base44] WARNING: BASE44_PUBLIC_HOST_SUFFIX is unset; browser Supabase URL will be invalid." >&2
fi

# SSR runs inside the container and reaches Supabase via the host gateway.
# The browser reaches Supabase through the platform's public port proxy.
cat > .env.supabase-runtime <<EOF
# Auto-generated by scripts/base44-start.sh — do not commit (gitignored).
SUPABASE_URL=http://host.docker.internal:54321
SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SECRET_KEY}
VITE_SUPABASE_URL=https://54321-${SUFFIX}
VITE_SUPABASE_PUBLISHABLE_KEY=${PUBLISHABLE_KEY}
EOF

echo "[base44] Starting the app (docker compose up)…"
docker compose -f docker-compose.base44.yml up -d --build
