/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as SkillsSlugRouteImport } from './routes/skills.$slug'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as AuthenticatedSessionsRouteImport } from './routes/_authenticated/sessions'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedExploreRouteImport } from './routes/_authenticated/explore'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated/sessions.$id'
import { Route as AuthenticatedProfileUserIdRouteImport } from './routes/_authenticated/profile.$userId'
import { Route as AuthenticatedLibraryIdRouteImport } from './routes/_authenticated/library.$id'
import { Route as AuthenticatedChallengesIdRouteImport } from './routes/_authenticated/challenges.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSessionsRoute = AuthenticatedSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExploreRoute = AuthenticatedExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedSessionsRoute,
} as any)
const AuthenticatedProfileUserIdRoute =
  AuthenticatedProfileUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedLibraryIdRoute = AuthenticatedLibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedLibraryRoute,
} as any)
const AuthenticatedChallengesIdRoute =
  AuthenticatedChallengesIdRouteImport.update({
    id: '/challenges/$id',
    path: '/challenges/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/challenges/$id': typeof AuthenticatedChallengesIdRoute
  '/library/$id': typeof AuthenticatedLibraryIdRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/explore': typeof AuthenticatedExploreRoute
  '/library': typeof AuthenticatedLibraryRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/challenges/$id': typeof AuthenticatedChallengesIdRoute
  '/library/$id': typeof AuthenticatedLibraryIdRoute
  '/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/explore': typeof AuthenticatedExploreRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/sessions': typeof AuthenticatedSessionsRouteWithChildren
  '/projects/$id': typeof ProjectsIdRoute
  '/skills/$slug': typeof SkillsSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/_authenticated/challenges/$id': typeof AuthenticatedChallengesIdRoute
  '/_authenticated/library/$id': typeof AuthenticatedLibraryIdRoute
  '/_authenticated/profile/$userId': typeof AuthenticatedProfileUserIdRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/community'
    | '/dashboard'
    | '/explore'
    | '/library'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/sessions'
    | '/projects/$id'
    | '/skills/$slug'
    | '/u/$handle'
    | '/challenges/$id'
    | '/library/$id'
    | '/profile/$userId'
    | '/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/community'
    | '/dashboard'
    | '/explore'
    | '/library'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/sessions'
    | '/projects/$id'
    | '/skills/$slug'
    | '/u/$handle'
    | '/challenges/$id'
    | '/library/$id'
    | '/profile/$userId'
    | '/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/explore'
    | '/_authenticated/library'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/sessions'
    | '/projects/$id'
    | '/skills/$slug'
    | '/u/$handle'
    | '/_authenticated/challenges/$id'
    | '/_authenticated/library/$id'
    | '/_authenticated/profile/$userId'
    | '/_authenticated/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  SkillsSlugRoute: typeof SkillsSlugRoute
  UHandleRoute: typeof UHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sessions': {
      id: '/_authenticated/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explore': {
      id: '/_authenticated/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AuthenticatedExploreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedSessionsRoute
    }
    '/_authenticated/profile/$userId': {
      id: '/_authenticated/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AuthenticatedProfileUserIdRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/library/$id': {
      id: '/_authenticated/library/$id'
      path: '/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof AuthenticatedLibraryIdRouteImport
      parentRoute: typeof AuthenticatedLibraryRoute
    }
    '/_authenticated/challenges/$id': {
      id: '/_authenticated/challenges/$id'
      path: '/challenges/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof AuthenticatedChallengesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedLibraryRouteChildren {
  AuthenticatedLibraryIdRoute: typeof AuthenticatedLibraryIdRoute
}

const AuthenticatedLibraryRouteChildren: AuthenticatedLibraryRouteChildren = {
  AuthenticatedLibraryIdRoute: AuthenticatedLibraryIdRoute,
}

const AuthenticatedLibraryRouteWithChildren =
  AuthenticatedLibraryRoute._addFileChildren(AuthenticatedLibraryRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileUserIdRoute: typeof AuthenticatedProfileUserIdRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileUserIdRoute: AuthenticatedProfileUserIdRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedSessionsRouteChildren {
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRoute
}

const AuthenticatedSessionsRouteChildren: AuthenticatedSessionsRouteChildren = {
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRoute,
}

const AuthenticatedSessionsRouteWithChildren =
  AuthenticatedSessionsRoute._addFileChildren(
    AuthenticatedSessionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExploreRoute: typeof AuthenticatedExploreRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedSessionsRoute: typeof AuthenticatedSessionsRouteWithChildren
  AuthenticatedChallengesIdRoute: typeof AuthenticatedChallengesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExploreRoute: AuthenticatedExploreRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedSessionsRoute: AuthenticatedSessionsRouteWithChildren,
  AuthenticatedChallengesIdRoute: AuthenticatedChallengesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  SkillsSlugRoute: SkillsSlugRoute,
  UHandleRoute: UHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
