-- ============================================================================
-- Skill catalog growth — more job/role-flavored categories with definitions
-- and tools (continues 20260808180000). Idempotent: ON CONFLICT (slug) UPDATE.
-- ============================================================================

INSERT INTO public.skills (slug, name, category, description, tools) VALUES
-- ── Health & Wellness ──────────────────────────────────────────────────────
('fitness-training','Fitness Training','Health & Wellness',
 'Coaching clients to build strength, mobility, and sustainable habits.',
 ARRAY['Trainerize','MyFitnessPal','Google Sheets','Apple Watch']),
('nutrition','Nutrition','Health & Wellness',
 'Designing eating plans around goals, allergies, and preferences.',
 ARRAY['Cronometer','MyFitnessPal','Notion','Health app']),
('yoga','Yoga','Health & Wellness',
 'Teaching breathwork, mobility, and strength through yoga practice.',
 ARRAY['Pocket Yoga','Zoom','Spotify','Alo Moves']),
('meditation','Meditation & Mindfulness','Health & Wellness',
 'Guiding practices that build focus, calm, and emotional regulation.',
 ARRAY['Calm','Headspace','Insight Timer','Zoom']),
('mental-health','Mental Health Support','Health & Wellness',
 'Supporting wellbeing with evidence-based conversation and coping tools.',
 ARRAY['BetterHelp','Notion','Calm','Headspace']),
('physiotherapy','Physiotherapy','Health & Wellness',
 'Rehabilitating movement and function after injury or surgery.',
 ARRAY['Goniometer apps','Google Sheets','Pro tools']),
('first-aid','First Aid & CPR','Health & Wellness',
 'Emergency response skills for injury and cardiac events.',
 ARRAY['Red Cross app','Manikins','AED trainers']),
('sleep-coaching','Sleep Coaching','Health & Wellness',
 'Improving sleep quality through routines, environment, and tracking.',
 ARRAY['Whoop','Oura','Sleep Cycle','Notion']),
('personal-training','Personal Training','Health & Wellness',
 'Designing and delivering one-on-one workout programming.',
 ARRAY['Trainerize','TrueCoach','Apple Watch','Form video apps']),

-- ── Finance & Business Ops ─────────────────────────────────────────────────
('accounting','Accounting','Finance',
 'Recording transactions and keeping books audit-ready.',
 ARRAY['QuickBooks','Xero','Wave','Excel']),
('bookkeeping','Bookkeeping','Finance',
 'Day-to-day financial record keeping for small businesses.',
 ARRAY['QuickBooks','Xero','Wave','Expensify']),
('financial-planning','Financial Planning','Finance',
 'Building budgets, savings, and investment plans for clients.',
 ARRAY['RightCapital','eMoney','Excel','Notion']),
('investing','Investing','Finance',
 'Analyzing markets and managing investment portfolios.',
 ARRAY['TradingView','Bloomberg Terminal','Excel','Thinkorswim']),
('stock-trading','Stock Trading','Finance',
 'Executing and managing equity trades with risk discipline.',
 ARRAY['TradingView','Thinkorswim','E*TRADE','FINVIZ']),
('crypto-trading','Crypto Trading','Finance',
 'Trading digital assets and managing on-chain positions.',
 ARRAY['Binance','Coinbase','TradingView','DeFi tools']),
('tax-prep','Tax Preparation','Finance',
 'Preparing and filing accurate tax returns for individuals and firms.',
 ARRAY['TurboTax','Drake Tax','ProConnect','IRS tools']),
('payroll','Payroll Management','Finance',
 'Running payroll accurately and on time for teams.',
 ARRAY['Gusto','ADP','QuickBooks Payroll','Rippling']),
('personal-finance','Personal Finance','Finance',
 'Managing income, spending, and saving toward financial goals.',
 ARRAY['YNAB','Mint','Monarch','Excel']),
('small-business-finance','Small Business Finance','Finance',
 'Cash flow, pricing, and funding for early-stage businesses.',
 ARRAY['QuickBooks','Stripe','Brex','LivePlan']),

-- ── Education & Tutoring ───────────────────────────────────────────────────
('tutoring','Tutoring','Education',
 'One-on-one instruction that meets students where they are.',
 ARRAY['Zoom','Google Classroom','Khan Academy','Notion']),
('esl-teaching','ESL Teaching','Education',
 'Teaching English to speakers of other languages.',
 ARRAY['Zoom','Kahoot','Quizlet','iTalki']),
('curriculum-design','Curriculum Design','Education',
 'Structuring courses and lessons around clear learning outcomes.',
 ARRAY['Notion','Google Docs','FigJam','H5P']),
('k12-teaching','K-12 Teaching','Education',
 'Teaching core subjects to elementary and secondary students.',
 ARRAY['Google Classroom','Seesaw','Canva','Kahoot']),
('early-childhood','Early Childhood Education','Education',
 'Nurturing learning and play for young children.',
 ARRAY['Brightwheel','ClassDojo','Canva','Lakeshore tools']),
('test-prep','Test Prep','Education',
 'Preparing students for SAT, ACT, GRE, and other exams.',
 ARRAY['Khan Academy','PrepScholar','Magoosh','Notion']),
('educational-technology','EdTech Tools','Education',
 'Using digital platforms to make teaching more effective.',
 ARRAY['Google Workspace','Canvas','Schoology','Padlet']),
('montessori','Montessori Education','Education',
 'Child-led learning rooted in Montessori principles.',
 ARRAY['Montessori Compass','Notion','Hands-on materials']),
('teacher-training','Teacher Training','Education',
 'Mentoring and professional development for educators.',
 ARRAY['Zoom','Notion','Google Slides','Padlet']),

-- ── Trades & Hands-on ──────────────────────────────────────────────────────
('carpentry','Carpentry','Trades & Hands-on',
 'Building and repairing structures with wood and joinery.',
 ARRAY['Circular saw','Table saw','Chisels','SketchUp']),
('welding','Welding','Trades & Hands-on',
 'Joining metal with heat for fabrication and repair.',
 ARRAY['MIG/TIG rigs','Angle grinder','Auto-darkening helmet']),
('plumbing','Plumbing','Trades & Hands-on',
 'Installing and repairing water, gas, and drainage systems.',
 ARRAY['Pipe wrenches','PEX tools','Inspection cameras']),
('electrical-work','Electrical Work','Trades & Hands-on',
 'Wiring and maintaining safe electrical systems.',
 ARRAY['Multimeter','Voltage testers','Wire strippers','Code books']),
('hvac','HVAC','Trades & Hands-on',
 'Installing and servicing heating, ventilation, and cooling.',
 ARRAY['Manifold gauges','Digital thermometers','Vacuum pumps']),
('auto-mechanics','Auto Mechanics','Trades & Hands-on',
 'Diagnosing and repairing vehicles.',
 ARRAY['OBD-II scanner','Socket sets','Lifts','AllData']),
('painting','Painting & Finishing','Trades & Hands-on',
 'Preparing and finishing surfaces with professional paintwork.',
 ARRAY['Sprayers','Brushes/rollers','Tape & masking','Color fans']),
('landscaping','Landscaping','Trades & Hands-on',
 'Designing and maintaining outdoor spaces and gardens.',
 ARRAY['Mowers','Trimmers','Irrigation kits','SketchUp']),
('sewing','Sewing & Tailoring','Trades & Hands-on',
 'Constructing and altering garments and soft goods.',
 ARRAY['Sewing machine','Serger','Irons','Pattern software']),
('jewelry-making','Jewelry Making','Trades & Hands-on',
 'Designing and fabricating jewelry by hand or with tools.',
 ARRAY['Bench tools','Torches','Casting kits','Rhino']),
('woodworking','Woodworking','Trades & Hands-on',
 'Crafting furniture and objects from wood.',
 ARRAY['Jointer/planer','CNC router','Hand tools','SketchUp']),

-- ── Sports & Coaching ──────────────────────────────────────────────────────
('sports-coaching','Sports Coaching','Sports & Coaching',
 'Developing athletes with drills, tactics, and feedback.',
 ARRAY['Hudl','TeamSnap','Sportsrecruits','Tablets']),
('football-coaching','Football Coaching','Sports & Coaching',
 'Teaching soccer fundamentals, tactics, and team play.',
 ARRAY['Hudl','Pitch apps','Cones & bibs','TeamSnap']),
('basketball-coaching','Basketball Coaching','Sports & Coaching',
 'Building skills, schemes, and conditioning for hoops.',
 ARRAY['Hudl','Krossover','Whistle','GymTimer']),
('martial-arts','Martial Arts','Sports & Coaching',
 'Teaching self-defense, discipline, and striking/grappling skills.',
 ARRAY['Heavy bags','Focus mitts','Mats','YouTube technique libraries']),
('swimming-coaching','Swimming Coaching','Sports & Coaching',
 'Teaching technique and conditioning in the water.',
 ARRAY['Finis Tempo Trainer','Garmin','Kickboards','GoPro']),
('tennis-coaching','Tennis Coaching','Sports & Coaching',
 'Developing stroke technique and match strategy.',
 ARRAY['Ball machines','SwingVision','Court booking apps']),
('strength-coaching','Strength & Conditioning','Sports & Coaching',
 'Programming strength, power, and conditioning for athletes.',
 ARRAY['TRAINR','Teambuildr','Force plates','Google Sheets']),

-- ── Hospitality & Service ──────────────────────────────────────────────────
('barista','Barista & Coffee','Hospitality',
 'Crafting espresso drinks and running a café bar.',
 ARRAY['Espresso machines','Grinders','Latte art tools','Receipt POS']),
('bartending','Bartending & Mixology','Hospitality',
 'Making cocktails, running a bar, and reading a room.',
 ARRAY['Shakers','Jiggers','Speed pourers','Difford''s Guide']),
('cooking','Cooking & Culinary','Hospitality',
 'Preparing delicious food across cuisines and diets.',
 ARRAY['Knives','Thermometers','Kitchen scale','Cooking apps']),
('baking','Baking & Pastry','Hospitality',
 'Baking bread, cakes, and pastries with precision.',
 ARRAY['Stand mixer','Oven thermometer','Scales','Proofing boxes']),
('event-planning','Event Planning','Hospitality',
 'Planning and running memorable events end to end.',
 ARRAY['Notion','Trello','Eventbrite','Canva']),
('wedding-planning','Wedding Planning','Hospitality',
 'Coordinating vendors, budgets, and timelines for weddings.',
 ARRAY['Aisle Planner','Allseated','HoneyBook','Google Sheets']),
('hotel-management','Hotel Management','Hospitality',
 'Running front desk, housekeeping, and guest experience.',
 ARRAY['Opera PMS','Cloudbeds','Booking engines','Review tools']),
('tour-guiding','Tour Guiding','Hospitality',
 'Leading tours and telling stories travelers remember.',
 ARRAY['TripAdvisor','Google Maps','Microphones','Canva']),
('restaurant-management','Restaurant Management','Hospitality',
 'Running operations, staff, and P&L for a restaurant.',
 ARRAY['Toast POS','7shifts','Xero','OpenTable']),

-- ── Law & Compliance ───────────────────────────────────────────────────────
('legal-research','Legal Research','Law & Compliance',
 'Finding and analyzing case law, statutes, and regulations.',
 ARRAY['Westlaw','LexisNexis','Casetext','Google Scholar']),
('contract-drafting','Contract Drafting','Law & Compliance',
 'Writing clear, enforceable agreements.',
 ARRAY['Microsoft Word','DocuSign','Lexis','Clause libraries']),
('immigration-law','Immigration Law','Law & Compliance',
 'Navigating visas, green cards, and citizenship processes.',
 ARRAY['USCIS tools','Case management software','DocuSign']),
('compliance','Compliance','Law & Compliance',
 'Keeping organizations aligned with rules and regulations.',
 ARRAY['Vanta','Drata','Jira','Excel']),
('privacy','Data Privacy','Law & Compliance',
 'Managing consent, rights, and GDPR/CCPA obligations.',
 ARRAY['OneTrust','Termly','Jira','Notion']),
('notary','Notarization','Law & Compliance',
 'Witnessing and authenticating legal documents.',
 ARRAY['Notary stamps','Remote notary platforms','Journal software']),

-- ── Science & Research ─────────────────────────────────────────────────────
('biology','Biology','Science & Research',
 'Studying living systems from cells to ecosystems.',
 ARRAY['Microscopes','BioRender','R','Notion']),
('chemistry','Chemistry','Science & Research',
 'Working with matter, reactions, and lab techniques.',
 ARRAY['Lab equipment','ChemDraw','R','ELN software']),
('physics','Physics','Science & Research',
 'Modeling and measuring the physical world.',
 ARRAY['Python','MATLAB','COMSOL','Lab equipment']),
('research','Research Methods','Science & Research',
 'Designing studies, collecting data, and writing findings.',
 ARRAY['Zotero','Qualtrics','SPSS','Google Scholar']),
('statistics','Statistical Analysis','Science & Research',
 'Applying statistics to real data for defensible conclusions.',
 ARRAY['R','Python','JASP','Excel']),

-- ── More creator / dev depth ───────────────────────────────────────────────
('short-form-video','Short-form Video','Creator Growth',
 'Editing fast-paced vertical video for reels and shorts.',
 ARRAY['CapCut','Premiere Pro','DaVinci Resolve','After Effects']),
('visual-design','Visual Design','Graphic Design',
 'Composing layouts, color, and type for any medium.',
 ARRAY['Figma','Photoshop','Illustrator','Canva']),
('database','PostgreSQL','Data & AI',
 'Designing schemas, queries, and indexes on Postgres.',
 ARRAY['PostgreSQL','pgAdmin','DBeaver','Supabase']),
('graphql','GraphQL','Web Development',
 'Designing typed APIs with flexible, efficient queries.',
 ARRAY['GraphQL','Apollo','Hasura','Postman']),
('caching','Redis & Caching','DevOps & Cloud',
 'Speeding up apps with caching and in-memory data.',
 ARRAY['Redis','Upstash','Docker','Grafana']),
('containers','Kubernetes','DevOps & Cloud',
 'Orchestrating containerized workloads at scale.',
 ARRAY['Kubernetes','Helm','ArgoCD','kubectl']),
('ci-cd','CI/CD Pipelines','DevOps & Cloud',
 'Automating build, test, and deploy pipelines.',
 ARRAY['GitHub Actions','GitLab CI','Jenkins','ArgoCD']),
('serverless','Serverless','DevOps & Cloud',
 'Shipping functions and apps without managing servers.',
 ARRAY['AWS Lambda','Vercel','Cloudflare Workers','Supabase Edge']),
('observability','Observability','DevOps & Cloud',
 'Logging, metrics, and tracing to understand production.',
 ARRAY['Grafana','Prometheus','Datadog','OpenTelemetry']),
('security','Security Testing','DevOps & Cloud',
 'Finding and fixing vulnerabilities before attackers do.',
 ARRAY['Burp Suite','OWASP ZAP','Nmap','Snyk']),
('content-marketing','Content Marketing','Marketing',
 'Creating content that attracts and converts an audience.',
 ARRAY['Notion','Surfer SEO','Canva','Buffer']),
('brand-strategy','Brand Strategy','Marketing',
 'Defining positioning, voice, and market narrative.',
 ARRAY['Miro','Notion','Figma','Google Trends']),
('product-strategy','Product Strategy','Business',
 'Choosing what to build next and why it will win.',
 ARRAY['Linear','Amplitude','Miro','Notion']),
('direct-response-copywriting','Direct Response Copywriting','Marketing',
 'Writing copy that drives clicks, signups, and sales.',
 ARRAY['Google Docs','Swiped.co','Notion','A/B test tools']),
('kinetic-typography','Kinetic Typography','Motion Design',
 'Animating type for titles, ads, and social video.',
 ARRAY['After Effects','Motion','Premiere Pro','Rive'])
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  tools = EXCLUDED.tools;
