-- ============================================================================
-- Enrich the skill catalog.
--
-- * Adds `description` (a one-line definition of the skill) and `tools`
--   (the apps/gear people use for it) columns.
-- * Upserts the full catalog — existing 44 skills get definitions + tools,
--   and ~85 new skills land across more job/role-style categories.
--
-- Idempotent: ON CONFLICT (slug) DO UPDATE enriches existing rows and makes
-- re-runs safe.
-- ============================================================================

ALTER TABLE public.skills
  ADD COLUMN IF NOT EXISTS description text,
  ADD COLUMN IF NOT EXISTS tools text[] NOT NULL DEFAULT '{}';

INSERT INTO public.skills (slug, name, category, description, tools) VALUES
-- ── Video Editing ──────────────────────────────────────────────────────────
('premiere-pro','Premiere Pro','Video Editing',
 'Professional nonlinear editing for film, broadcast, and online video.',
 ARRAY['Premiere Pro','Media Encoder','After Effects','Frame.io']),
('davinci-resolve','DaVinci Resolve','Video Editing',
 'All-in-one editing, color grading, and finishing suite.',
 ARRAY['DaVinci Resolve','Fusion','Fairlight','DaVinci Color']),
('final-cut-pro','Final Cut Pro','Video Editing',
 'Apple''s magnetic-timeline editor for Mac creators.',
 ARRAY['Final Cut Pro','Motion','Compressor','Logic Pro']),
('capcut','CapCut','Video Editing',
 'Fast, template-driven short-form video editing.',
 ARRAY['CapCut','CapCut Pro','TikTok']),
('video-editing','Video Editing','Video Editing',
 'Cutting, sequencing, and shaping footage into a finished story.',
 ARRAY['Premiere Pro','DaVinci Resolve','CapCut','Final Cut Pro']),
('color-grading','Color Grading','Video Editing',
 'Styling and balancing footage to create a consistent look.',
 ARRAY['DaVinci Resolve','Color Finale','Lumetri','Filmora']),
('subtitle-captioning','Subtitles & Captioning','Video Editing',
 'Adding accurate, styled captions and subtitles to video.',
 ARRAY['CapCut','Subtitle Edit','Descript','YouTube Studio']),
('podcast-editing','Podcast Editing','Video Editing',
 'Cleaning up and producing audio for podcast episodes.',
 ARRAY['Audacity','Descript','Hindenburg','Adobe Audition']),

-- ── Motion Design & Animation ─────────────────────────────────────────────
('after-effects','After Effects','Motion Design',
 'Industry-standard motion graphics and compositing.',
 ARRAY['After Effects','Mocha','Element 3D','Bodymovin']),
('motion-graphics','Motion Graphics','Motion Design',
 'Animated graphics for titles, logos, explainers, and ads.',
 ARRAY['After Effects','Cavalry','Rive','Motion']),
('2d-animation','2D Animation','Motion Design',
 'Frame-by-frame and rigged animation for characters and motion.',
 ARRAY['Toon Boom Harmony','Spine','Procreate Dreams','After Effects']),
('character-animation','Character Animation','Motion Design',
 'Bringing rigged or hand-drawn characters to life.',
 ARRAY['Blender','Maya','Cascadeur','Spine']),

-- ── 3D & VFX ──────────────────────────────────────────────────────────────
('blender','Blender','3D',
 'Free, open-source 3D modeling, sculpting, animation, and rendering.',
 ARRAY['Blender','Cycles','Eevee','Geometry Nodes']),
('cinema-4d','Cinema 4D','3D',
 'Motion-design-first 3D tool used across advertising and broadcast.',
 ARRAY['Cinema 4D','Redshift','Octane','X-Particles']),
('3d-modeling','3D Modeling','3D',
 'Creating 3D assets for games, film, product viz, and print.',
 ARRAY['Blender','ZBrush','Maya','Substance 3D']),
('rigging','Rigging','3D',
 'Building the skeleton and controls that let 3D characters move.',
 ARRAY['Blender','Maya','Auto-Rig Pro']),
('visual-effects','Visual Effects','3D',
 'Compositing CGI with live action and selling the impossible.',
 ARRAY['After Effects','Nuke','Houdini','Fusion']),
('unreal-engine','Unreal Engine','3D',
 'Real-time 3D engine for games, archviz, and virtual production.',
 ARRAY['Unreal Engine 5','Blueprints','Quixel','MetaHuman']),
('unity','Unity','3D',
 'Real-time engine for 2D/3D games, XR, and interactive media.',
 ARRAY['Unity','Shader Graph','C#','Bolt']),
('godot','Godot','3D',
 'Open-source 2D/3D game engine with a friendly scene system.',
 ARRAY['Godot','GDScript','Godot Shaders']),

-- ── Graphic Design ────────────────────────────────────────────────────────
('photoshop','Photoshop','Graphic Design',
 'Raster image editing, compositing, and digital art.',
 ARRAY['Photoshop','Camera Raw','Lightroom','Generative Fill']),
('illustrator','Illustrator','Graphic Design',
 'Vector illustration, logos, and print graphics.',
 ARRAY['Illustrator','InDesign','Figma']),
('canva','Canva','Graphic Design',
 'Browser-based design for social, docs, and presentations.',
 ARRAY['Canva','Canva Pro','Magic Studio']),
('logo-design','Logo Design','Graphic Design',
 'Designing memorable marks and identity systems.',
 ARRAY['Illustrator','Figma','Procreate']),
('illustration','Illustration','Graphic Design',
 'Hand-drawn and digital imagery for media, books, and brands.',
 ARRAY['Procreate','Photoshop','Clip Studio Paint','Illustrator']),
('digital-painting','Digital Painting','Graphic Design',
 'Painting directly on a tablet or screen.',
 ARRAY['Procreate','Photoshop','Krita','Corel Painter']),
('print-design','Print Design','Graphic Design',
 'Design for posters, packaging, and physical media.',
 ARRAY['InDesign','Illustrator','Photoshop','Acrobat']),
('presentation-design','Presentation Design','Graphic Design',
 'Turning ideas into clear, polished slide decks.',
 ARRAY['PowerPoint','Keynote','Figma','Google Slides']),

-- ── Design & Product ──────────────────────────────────────────────────────
('figma','Figma','Design',
 'Collaborative interface design and prototyping.',
 ARRAY['Figma','FigJam','Penpot','Framer']),
('branding','Branding','Design',
 'Defining a brand''s strategy, voice, and visual identity.',
 ARRAY['Illustrator','Figma','InDesign','Miro']),
('typography','Typography','Design',
 'Choosing and crafting type for readability and impact.',
 ARRAY['Adobe Fonts','Google Fonts','Figma','Glyphs']),
('ui-design','UI Design','Design',
 'Designing the screens, components, and states of a product.',
 ARRAY['Figma','Sketch','Penpot','Framer']),
('ux-design','UX Design','Design',
 'Designing flows and experiences that are easy to use.',
 ARRAY['Figma','Miro','Maze','Notion']),
('ux-research','UX Research','Design',
 'Studying users to inform product decisions.',
 ARRAY['Maze','UserTesting','Dovetail','Hotjar']),
('product-design','Product Design','Design',
 'End-to-end design of digital products, from problem to shipped UI.',
 ARRAY['Figma','Notion','Principle','Linear']),
('web-design','Web Design','Design',
 'Designing responsive websites that balance brand and conversion.',
 ARRAY['Figma','Webflow','Framer','Photoshop']),

-- ── Photography ───────────────────────────────────────────────────────────
('lightroom','Lightroom','Photography',
 'Photo library management and non-destructive raw editing.',
 ARRAY['Lightroom Classic','Lightroom CC','Camera Raw']),
('photography','Photography','Photography',
 'Capturing and editing images across any genre.',
 ARRAY['Lightroom','Photoshop','Capture One']),
('portrait-photography','Portrait Photography','Photography',
 'Directing and lighting people for compelling portraits.',
 ARRAY['Lightroom','Photoshop','Profoto','Capture One']),
('product-photography','Product Photography','Photography',
 'Making products look their best for stores and campaigns.',
 ARRAY['Capture One','Lightroom','Photoshop','Tabletop rigs']),
('wedding-photography','Wedding Photography','Photography',
 'Documenting weddings with speed and discretion.',
 ARRAY['Lightroom','Capture One','Photoshop','Canon/ Sony bodies']),
('event-photography','Event Photography','Photography',
 'Capturing live events, conferences, and concerts.',
 ARRAY['Lightroom','Photoshop','Dual bodies']),
('drone-photography','Drone Photography','Photography',
 'Aerial photos and cinematic drone footage.',
 ARRAY['DJI Fly','Lightroom','Premiere Pro']),
('photo-retouching','Photo Retouching','Photography',
 'Skin, color, and detail work that makes images flawless.',
 ARRAY['Photoshop','Capture One','Portraiture']),

-- ── Audio & Music ─────────────────────────────────────────────────────────
('sound-design','Sound Design','Audio',
 'Creating and placing audio elements that shape how a piece feels.',
 ARRAY['Pro Tools','Ableton Live','iZotope RX','Foley kits']),
('music-production','Music Production','Audio',
 'Producing, arranging, and recording full tracks.',
 ARRAY['Ableton Live','Logic Pro','FL Studio','Pro Tools']),
('ableton-live','Ableton Live','Audio',
 'DAW built for electronic production and live performance.',
 ARRAY['Ableton Live','Max for Live','Push']),
('logic-pro','Logic Pro','Audio',
 'Apple''s DAW for recording, editing, and mixing.',
 ARRAY['Logic Pro','MainStage','GarageBand']),
('flstudio','FL Studio','Audio',
 'Beat and track production with a pattern-based workflow.',
 ARRAY['FL Studio','Serum','Kontakt','Gross Beat']),
('mixing-mastering','Mixing & Mastering','Audio',
 'Balancing a mix and finalizing loudness and clarity.',
 ARRAY['Pro Tools','iZotope Ozone','Ableton Live','FabFilter']),
('songwriting','Songwriting','Audio',
 'Writing lyrics, melodies, and structure that land.',
 ARRAY['Logic Pro','GarageBand','Notes app']),
('beat-making','Beat Making','Audio',
 'Programming drums, chords, and grooves for tracks.',
 ARRAY['FL Studio','Ableton Live','MPC','Serum']),
('voice-over','Voice Over','Audio',
 'Recording clean, characterful narration and commercial reads.',
 ARRAY['Audacity','TwistedWave','Adobe Audition','Booth setup']),
('live-sound','Live Sound','Audio',
 'Mixing and managing audio for live events.',
 ARRAY['Mixers','QLab','Smaart','Wireless systems']),

-- ── Marketing & Growth ────────────────────────────────────────────────────
('seo','SEO','Marketing',
 'Making pages rank and earn organic traffic from search.',
 ARRAY['Google Search Console','Ahrefs','Semrush','Screaming Frog']),
('social-media','Social Media Strategy','Marketing',
 'Planning and posting content that grows an audience.',
 ARRAY['Meta Business Suite','Hootsuite','Buffer','Later']),
('copywriting','Copywriting','Marketing',
 'Writing words that sell — ads, emails, landing pages, and hooks.',
 ARRAY['Google Docs','Notion','Grammarly','Hemingway']),
('content-strategy','Content Strategy','Marketing',
 'Planning content that attracts and converts an audience.',
 ARRAY['Notion','Airtable','Google Trends','Semrush']),
('email-marketing','Email Marketing','Marketing',
 'Building lists and writing campaigns that people open.',
 ARRAY['Mailchimp','Klaviyo','ConvertKit','Beehiiv']),
('digital-marketing','Digital Marketing','Marketing',
 'Running multi-channel acquisition across search and social.',
 ARRAY['Google Ads','Meta Ads Manager','GA4','Ahrefs']),
('paid-ads','Paid Advertising','Marketing',
 'Buying and optimizing traffic on ad platforms.',
 ARRAY['Google Ads','Meta Ads Manager','TikTok Ads','Reddit Ads']),
('web-analytics','Web Analytics','Marketing',
 'Measuring traffic and behavior to drive decisions.',
 ARRAY['GA4','Plausible','Mixpanel','Hotjar']),
('growth-marketing','Growth Marketing','Marketing',
 'Rapid experimentation to compound acquisition and retention.',
 ARRAY['Mixpanel','Amplitude','PostHog','GA4']),
('affiliate-marketing','Affiliate Marketing','Marketing',
 'Earning commissions by promoting products and services.',
 ARRAY['ShareASale','Amazon Associates','Impact']),

-- ── Writing ───────────────────────────────────────────────────────────────
('scriptwriting','Scriptwriting','Writing',
 'Writing scripts for video, film, and long-form content.',
 ARRAY['Final Draft','Fade In','Highland','Notion']),
('creative-writing','Creative Writing','Writing',
 'Crafting fiction, poetry, and narrative prose.',
 ARRAY['Scrivener','Notion','Google Docs']),
('technical-writing','Technical Writing','Writing',
 'Documenting products clearly for developers and users.',
 ARRAY['Markdown','GitBook','Notion','ReadMe']),
('blogging','Blogging','Writing',
 'Writing and publishing articles that build an audience.',
 ARRAY['WordPress','Ghost','Notion','Surfer SEO']),
('proofreading','Editing & Proofreading','Writing',
 'Catching errors and polishing copy before it ships.',
 ARRAY['Grammarly','PerfectIt','Google Docs']),
('translation','Translation','Writing',
 'Translating content accurately between languages.',
 ARRAY['DeepL','Smartcat','Crowdin','Trados']),

-- ── Web Development ───────────────────────────────────────────────────────
('wordpress','WordPress','Web Development',
 'Building sites and shops on the world''s most-used CMS.',
 ARRAY['WordPress','Elementor','WooCommerce','WP Engine']),
('webflow','Webflow','Web Development',
 'Designing and launching production sites without code.',
 ARRAY['Webflow','Finsweet','Memberstack','Wized']),
('html-css','HTML & CSS','Web Development',
 'The markup and styling foundation of every website.',
 ARRAY['VS Code','Chrome DevTools','Tailwind CSS']),
('javascript','JavaScript','Web Development',
 'The language that powers interactive web apps.',
 ARRAY['VS Code','Node.js','Chrome DevTools','TypeScript']),
('typescript','TypeScript','Web Development',
 'Typed JavaScript for safer, more maintainable apps.',
 ARRAY['VS Code','tsc','TypeScript ESLint']),
('react','React','Web Development',
 'Component-based library for building interfaces.',
 ARRAY['React','Next.js','Vite','React DevTools']),
('nextjs','Next.js','Web Development',
 'React framework with routing, SSR, and edge deployment.',
 ARRAY['Next.js','Vercel','Tailwind CSS','Vercel AI SDK']),
('vue','Vue.js','Web Development',
 'Approachable framework for interactive interfaces.',
 ARRAY['Vue','Nuxt','Vite','Pinia']),
('svelte','Svelte','Web Development',
 'Compile-first framework for fast, tiny web apps.',
 ARRAY['Svelte','SvelteKit','Vite']),
('tailwind-css','Tailwind CSS','Web Development',
 'Utility-first CSS for rapid, consistent styling.',
 ARRAY['Tailwind CSS','VS Code','Headless UI']),
('nodejs','Node.js','Web Development',
 'JavaScript runtime for servers, tools, and APIs.',
 ARRAY['Node.js','Express','Fastify','npm']),
('backend-development','Backend Development','Web Development',
 'Building the servers, APIs, and data layers behind apps.',
 ARRAY['Node.js','PostgreSQL','Docker','Redis']),

-- ── Data & Databases ──────────────────────────────────────────────────────
('python','Python','Data & AI',
 'General-purpose language for automation, data, and AI.',
 ARRAY['Python','VS Code','Jupyter','pip']),
('sql','SQL','Data & AI',
 'Querying and shaping data in relational databases.',
 ARRAY['PostgreSQL','SQLite','DataGrip','DBeaver']),
('database-design','Database Design','Data & AI',
 'Modeling schemas that stay fast and easy to evolve.',
 ARRAY['PostgreSQL','DBeaver','dbdiagram.io']),
('api-development','API Development','Data & AI',
 'Designing and building clean, documented APIs.',
 ARRAY['Postman','FastAPI','Express','OpenAPI']),
('data-analysis','Data Analysis','Data & AI',
 'Turning raw data into insights and decisions.',
 ARRAY['Python','pandas','SQL','Excel']),
('data-science','Data Science','Data & AI',
 'Using statistics and ML to extract knowledge from data.',
 ARRAY['Python','scikit-learn','Jupyter','pandas']),
('machine-learning','Machine Learning','Data & AI',
 'Training models that learn patterns from data.',
 ARRAY['PyTorch','TensorFlow','scikit-learn','Hugging Face']),
('data-visualization','Data Visualization','Data & AI',
 'Designing charts and dashboards that communicate.',
 ARRAY['Tableau','Power BI','D3.js','Observable']),
('excel','Excel & Spreadsheets','Data & AI',
 'Modeling, analyzing, and presenting with spreadsheets.',
 ARRAY['Excel','Google Sheets','Sheets formulas']),
('power-bi','Power BI','Data & AI',
 'Building interactive dashboards from business data.',
 ARRAY['Power BI','DAX','Power Query']),

-- ── AI & Automation ───────────────────────────────────────────────────────
('ai-tools','AI Tools','AI & Automation',
 'Working productively with LLMs, image, and video AI.',
 ARRAY['ChatGPT','Claude','Midjourney','Runway']),
('prompt-engineering','Prompt Engineering','AI & Automation',
 'Crafting prompts that get reliable, high-quality AI output.',
 ARRAY['ChatGPT','Claude','Gemini','LangChain']),
('ai-agents','AI Agents','AI & Automation',
 'Building autonomous workflows that use LLMs to act.',
 ARRAY['LangChain','Claude Agent SDK','n8n','Zapier']),
('ai-art','AI Art Generation','AI & Automation',
 'Generating and refining images with diffusion models.',
 ARRAY['Midjourney','Stable Diffusion','ComfyUI','Leonardo']),
('automation','Automation & Workflows','AI & Automation',
 'Removing busywork with scripts, no-code, and integrations.',
 ARRAY['Zapier','n8n','Make','Python']),

-- ── DevOps & Cloud ────────────────────────────────────────────────────────
('cloud-computing','Cloud Computing','DevOps & Cloud',
 'Running applications on AWS, GCP, or Azure.',
 ARRAY['AWS','Google Cloud','Azure','Terraform']),
('devops','DevOps','DevOps & Cloud',
 'Automating build, deploy, and infrastructure.',
 ARRAY['Docker','Kubernetes','GitHub Actions','Terraform']),
('docker','Docker','DevOps & Cloud',
 'Packaging apps into portable containers.',
 ARRAY['Docker','Docker Compose','Kubernetes','Portainer']),
('git','Git & Version Control','DevOps & Cloud',
 'Tracking changes and collaborating on code.',
 ARRAY['Git','GitHub','GitLab','GitKraken']),
('software-testing','Software Testing','DevOps & Cloud',
 'Writing automated tests that keep software reliable.',
 ARRAY['Jest','Playwright','Cypress','Vitest']),
('web-performance','Web Performance','DevOps & Cloud',
 'Making sites load and interact quickly.',
 ARRAY['Lighthouse','WebPageTest','Chrome DevTools']),
('accessibility','Accessibility','DevOps & Cloud',
 'Building products everyone can use, regardless of ability.',
 ARRAY['axe DevTools','Lighthouse','NVDA','VoiceOver']),

-- ── Mobile & Game Dev ─────────────────────────────────────────────────────
('mobile-development','Mobile Development','Mobile & Game Dev',
 'Building native and cross-platform mobile apps.',
 ARRAY['React Native','Flutter','Xcode','Android Studio']),
('react-native','React Native','Mobile & Game Dev',
 'Building iOS and Android apps with React.',
 ARRAY['React Native','Expo','React Navigation']),
('flutter','Flutter','Mobile & Game Dev',
 'Cross-platform UI toolkit from a single Dart codebase.',
 ARRAY['Flutter','Dart','Android Studio']),
('swift','Swift / iOS','Mobile & Game Dev',
 'Building native iOS and macOS apps.',
 ARRAY['Xcode','Swift','SwiftUI','CocoaPods']),
('kotlin','Kotlin / Android','Mobile & Game Dev',
 'Building native Android apps.',
 ARRAY['Android Studio','Kotlin','Jetpack Compose']),
('game-design','Game Design','Mobile & Game Dev',
 'Designing mechanics, levels, and systems players love.',
 ARRAY['Unity','Unreal Engine','Figma','Miro']),

-- ── Streaming & Creator ───────────────────────────────────────────────────
('streaming','Streaming','Streaming',
 'Producing and broadcasting live content.',
 ARRAY['OBS Studio','Streamlabs','Twitch','Elgato']),
('obs','OBS Studio','Streaming',
 'Open-source software for live streaming and recording.',
 ARRAY['OBS Studio','Streamlabs OBS','Elgato Stream Deck']),
('twitch-growth','Twitch Growth','Streaming',
 'Growing a channel with consistent, entertaining streams.',
 ARRAY['Twitch','StreamElements','Nightbot','OBS']),
('youtube-growth','YouTube Growth','Creator Growth',
 'Growing a channel through packaging, pacing, and consistency.',
 ARRAY['YouTube Studio','VidIQ','TubeBuddy','Adobe Express']),
('thumbnail-design','Thumbnail Design','Creator Growth',
 'Designing click-worthy video thumbnails.',
 ARRAY['Photoshop','Canva','Figma','Adobe Express']),
('tiktok-growth','TikTok Growth','Creator Growth',
 'Making short-form videos that get discovered.',
 ARRAY['TikTok','CapCut','Trend Discovery']),
('instagram-growth','Instagram Growth','Creator Growth',
 'Growing an audience with reels, posts, and stories.',
 ARRAY['Instagram','Later','Meta Business Suite']),
('storytelling','Storytelling','Creator Growth',
 'Structuring narrative that keeps people watching.',
 ARRAY['Notion','Final Draft','CapCut']),
('content-creation','Content Creation','Creator Growth',
 'Planning, producing, and publishing content across formats.',
 ARRAY['CapCut','Canva','Notion','OBS Studio']),
('podcasting','Podcasting','Creator Growth',
 'Launching and producing a podcast people subscribe to.',
 ARRAY['Descript','Audacity','Riverside','Buzzsprout']),
('video-production','Video Production','Creator Growth',
 'Full production — pre, shoot, and post — for video.',
 ARRAY['Premiere Pro','DaVinci Resolve','OBS Studio','LumaFusion']),
('online-courses','Course Creation','Creator Growth',
 'Turning expertise into structured, sellable lessons.',
 ARRAY['Teachable','Gumroad','Notion','Loom']),
('public-speaking','Public Speaking','Creator Growth',
 'Presenting ideas clearly and persuasively on stage or screen.',
 ARRAY['Keynote','Canva','OBS Studio','Notion']),

-- ── Community & Business ──────────────────────────────────────────────────
('community-management','Community Management','Community',
 'Growing and caring for an engaged online community.',
 ARRAY['Discord','Slack','Circle','Notion']),
('discord-communities','Discord Communities','Community',
 'Building and moderating thriving Discord servers.',
 ARRAY['Discord','MEE6','Discord Bots']),
('project-management','Project Management','Business',
 'Planning work and shipping it on time with a team.',
 ARRAY['Notion','Asana','Linear','Trello']),
('product-management','Product Management','Business',
 'Deciding what to build and aligning the team around it.',
 ARRAY['Linear','Figma','Notion','Amplitude']),
('freelancing','Freelancing','Business',
 'Running your own client work — pitching, pricing, delivering.',
 ARRAY['Notion','Stripe','HoneyBook','Calendly']),
('ecommerce','E-commerce','Business',
 'Selling products online across stores and marketplaces.',
 ARRAY['Shopify','WooCommerce','Klaviyo','Stripe']),
('shopify','Shopify','Business',
 'Building and growing a Shopify store.',
 ARRAY['Shopify','Klaviyo','Judge.me','Liquid']),
('sales','Sales','Business',
 'Finding prospects and closing deals.',
 ARRAY['HubSpot','Salesforce','Stripe','Calendly']),
('operations','Operations','Business',
 'Running the day-to-day systems a business depends on.',
 ARRAY['Notion','Airtable','Slack','Zapier']),
('no-code','No-Code Development','Business',
 'Shipping real products with tools instead of code.',
 ARRAY['Bubble','Webflow','Airtable','Zapier']),

-- ── Development (general + languages kept for backward compat) ────────────
('programming','Programming','Development',
 'Writing code to solve problems and build software.',
 ARRAY['VS Code','GitHub','Terminal','Cursor']),
('rust','Rust','Development',
 'Systems language with fearless performance and safety.',
 ARRAY['Rust','Cargo','VS Code','rust-analyzer']),
('go','Go','Development',
 'Simple, fast language for servers and cloud tools.',
 ARRAY['Go','VS Code','Docker']),
('csharp','C# / .NET','Development',
 'Microsoft''s language for apps, games, and services.',
 ARRAY['Visual Studio','.NET','Unity']),
('cplusplus','C++','Development',
 'High-performance language for engines and systems.',
 ARRAY['Visual Studio','CMake','Clang']),
('crypto-web3','Web3 & Crypto','Development',
 'Building on-chain apps and smart contracts.',
 ARRAY['Solidity','Foundry','Hardhat','Ethers.js'])
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  tools = EXCLUDED.tools;

-- A tiny guard so nothing above silently misses enrichment (informational).
COMMENT ON COLUMN public.skills.description IS 'One-line definition of the skill.';
COMMENT ON COLUMN public.skills.tools IS 'Apps and gear people commonly use for this skill.';
